[tool.towncrier]
    package = "towncrier"
    filename = "CHANGELOG.md"
    underlines = ["-", "", ""]
    template = "towncrier/template.md"
    title_format = "v{version} - {project_date}"
    issue_format = "[#{issue}](https://github.com/Mailu/Mailu/issues/{issue})"
    start_string = "<!-- TOWNCRIER -->"

[tool.black]
line-length = 90

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 90
