version: '3'


services:
  docs_master:
    image: mailu/docs:master
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.main.frontend.rule=Host:${hostname};PathPrefix:/master/

  docs_15:
    image: mailu/docs:1.5
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.root.frontend.redirect.regex=.*
      - traefik.root.frontend.redirect.replacement=/1.5/
      - traefik.root.frontend.rule=Host:${hostname};PathPrefix:/
      - traefik.main.frontend.rule=Host:${hostname};PathPrefix:/1.5/

