# This file is used to test the mailu/docs website
# Deployment files can be found on github.com/mailu/infra

version: '3'

services:
  docs:
    image: ${DOCKER_ORG:-mailu}/docs:${MAILU_VERSION:-master}
    ports:
      - 127.0.0.1:8000:80
