<?php
$labels = [];
$labels['mailu'] = 'Mailu';
$labels['changepassword'] = 'Change Password';
$labels['curpasswd'] = 'Current Password';
$labels['newpasswd'] = 'New Password';
$labels['confpasswd'] = 'Confirm New Password';
$labels['nocurpassword'] = 'Please enter your current password';
$labels['nonewpassword'] = 'Please enter a new password';
$labels['passwordinconsistency'] = 'Passwords do not match, please try again';
$labels['samepasswordfailed'] = 'New password must be different from the current password';
$labels['errorsaving'] = 'Unable to save password';
$labels['successfullysaved'] = 'Password changed successfully';
?>
